# Generated by Django 4.2.7 on 2025-11-26 02:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del modelo')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('liters_per_unit', models.DecimalField(decimal_places=4, help_text='Factor de conversión: 1 unidad del contador = X litros', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Litros por unidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Contador',
                'verbose_name_plural': 'Modelos de Contadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(help_text='Identificador único del contador físico', max_length=50, unique=True, verbose_name='ID del Contador')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('installation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de instalación')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='meters.metermodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'ordering': ['meter_id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_value', models.DecimalField(decimal_places=2, help_text='Valor acumulado mostrado en el contador', max_digits=15, verbose_name='Valor acumulado')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.meter', verbose_name='Contador')),
            ],
            options={
                'verbose_name': 'Lectura de Consumo',
                'verbose_name_plural': 'Lecturas de Consumo',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['meter', '-timestamp'], name='meters_cons_meter_i_7b2aff_idx')],
            },
        ),
    ]
